name: Build and Publish Docker image on GitHub Release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ toLower(github.repository) }}
  VERSION_FILE: version.txt

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # for updating version.txt + release
      packages: write       # for GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version.txt
        id: read_version
        run: |
          version=$(cat ${{ env.VERSION_FILE }})
          echo "VERSION_TXT=$version" >> $GITHUB_ENV
          echo "Read version.txt: $version"

      - name: Get latest GitHub release
        id: get_latest
        run: |
          latest=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)

          if [[ "$latest" == "null" || -z "$latest" ]]; then
            latest="v0.0.0"
          fi

          echo "LATEST_RELEASE_TAG=$latest" >> $GITHUB_ENV
          echo "Latest GitHub release: $latest"

      - name: Determine final version
        id: set_version
        run: |
          version_txt="${{ env.VERSION_TXT }}"
          latest_release="${LATEST_RELEASE_TAG#v}"  # strip leading "v" safely

          echo "version.txt = $version_txt"
          echo "latest release = $latest_release"

          if [[ "$version_txt" == "$latest_release" ]]; then
            IFS='.' read -r major minor patch <<< "$version_txt"
            patch=$((patch + 1))
            final="${major}.${minor}.${patch}"
            echo "Matched release tag, bumped to: $final"
            echo "UPDATED_VERSION=true" >> $GITHUB_ENV
          else
            final="$version_txt"
            echo "Using version.txt: $final"
            echo "UPDATED_VERSION=false" >> $GITHUB_ENV
          fi

          echo "FINAL_VERSION=$final" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.jazzy
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FINAL_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.FINAL_VERSION }}
          name: Release v${{ env.FINAL_VERSION }}
          body: |
            Automated Docker release v${{ env.FINAL_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.txt if bumped
        if: env.UPDATED_VERSION == 'true'
        run: |
          echo "${{ env.FINAL_VERSION }}" > ${{ env.VERSION_FILE }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ env.VERSION_FILE }}
          git commit -m "Update version.txt to ${{ env.FINAL_VERSION }}"
          git push
